#!/bin/sh

astyle \
  --options=none \
  --style=1tbs \
  --convert-tabs \
  --indent=spaces=2 \
  --indent-switches \
  --max-instatement-indent=60 \
  --pad-header \
  -r \
      '*.c' \
      '*.h' \
      '*.inc'
